const countries = [
  { label: "Afghanistan", value: "afghanistan" },
  { label: "Albania", value: "albania" },
  { label: "Algeria", value: "algeria" },
  { label: "American Samoa", value: "american-samoa" },
  { label: "Andorra", value: "andorra" },
  { label: "Angola", value: "angola" },
  { label: "Anguilla", value: "anguilla" },
  { label: "Antigua and Barbuda", value: "antigua-and-barbuda" },
  { label: "Argentina", value: "argentina" },
  { label: "Armenia", value: "armenia" },
  { label: "Aruba", value: "aruba" },
  { label: "Australia", value: "australia" },
  { label: "Austria", value: "austria" },
  { label: "Azerbaijan", value: "azerbaijan" },
  { label: "Bahamas", value: "bahamas" },
  { label: "Bahrain", value: "bahrain" },
  { label: "Bangladesh", value: "bangladesh" },
  { label: "Barbados", value: "barbados" },
  { label: "Belarus", value: "belarus" },
  { label: "Belgium", value: "belgium" },
  { label: "Belize", value: "belize" },
  { label: "Benin", value: "benin" },
  { label: "Bermuda", value: "bermuda" },
  { label: "Bhutan", value: "bhutan" },
  { label: "Bolivia", value: "bolivia" },
  {
    label: "Bonaire, Sint Eustatius and Saba",
    value: "bonaire-st-eustatius-saba",
  },
  { label: "Bosnia and Herzegovina", value: "bosnia-and-herzegovina" },
  { label: "Botswana", value: "botswana" },
  { label: "Brazil", value: "brazil" },
  { label: "British Virgin Islands", value: "british-virgin-islands" },
  { label: "Brunei", value: "brunei" },
  { label: "Bulgaria", value: "bulgaria" },
  { label: "Burkina Faso", value: "burkina-faso" },
  { label: "Burundi", value: "burundi" },
  { label: "Cambodia", value: "cambodia" },
  { label: "Cameroon", value: "cameroon" },
  { label: "Canada", value: "canada" },
  { label: "Cape Verde", value: "cape-verde" },
  { label: "Cayman Islands", value: "cayman-islands" },
  { label: "Central African Republic", value: "central-african-republic" },
  { label: "Chad", value: "chad" },
  { label: "Chile", value: "chile" },
  { label: "China", value: "china" },
  { label: "Colombia", value: "colombia" },
  { label: "Comoros", value: "comoros" },
  { label: "Congo", value: "congo" },
  { label: "Costa Rica", value: "costa-rica" },
  { label: "Croatia", value: "croatia" },
  { label: "Cuba", value: "cuba" },
  { label: "Curacao", value: "curacao" },
  { label: "Cyprus", value: "cyprus" },
  { label: "Czech Republic", value: "czech-republic" },
  { label: "Denmark", value: "denmark" },
  { label: "Djibouti", value: "djibouti" },
  { label: "Dominica", value: "dominica" },
  { label: "Dominican Republic", value: "dominican-republic" },
  { label: "DR Congo", value: "dr-congo" },
  { label: "East Timor", value: "east-timor" },
  { label: "Ecuador", value: "ecuador" },
  { label: "Egypt", value: "egypt" },
  { label: "El Salvador", value: "el-salvador" },
  { label: "Equatorial Guinea", value: "equatorial-guinea" },
  { label: "Eritrea", value: "eritrea" },
  { label: "Estonia", value: "estonia" },
  { label: "Eswatini", value: "swaziland" },
  { label: "Ethiopia", value: "ethiopia" },
  { label: "Faroe Islands", value: "faroe-islands" },
  { label: "Fiji", value: "fiji" },
  { label: "Finland", value: "finland" },
  { label: "France", value: "france" },
  { label: "French Guiana", value: "french-guiana" },
  { label: "French Polynesia", value: "french-polynesia" },
  { label: "Gabon", value: "gabon" },
  { label: "Gambia", value: "gambia" },
  { label: "Georgia", value: "georgia" },
  { label: "Germany", value: "germany" },
  { label: "Ghana", value: "ghana" },
  { label: "Gibraltar", value: "gibraltar" },
  { label: "Greece", value: "greece" },
  { label: "Greenland", value: "greenland" },
  { label: "Grenada", value: "grenada" },
  { label: "Guadeloupe", value: "guadeloupe" },
  { label: "Guam", value: "guam" },
  { label: "Guatemala", value: "guatemala" },
  { label: "Guernsey", value: "guernsey" },
  { label: "Guinea", value: "guinea" },
  { label: "Guinea-Bissau", value: "guinea-bissau" },
  { label: "Guyana", value: "guyana" },
  { label: "Haiti", value: "haiti" },
  { label: "Honduras", value: "honduras" },
  { label: "Hong Kong", value: "hong-kong" },
  { label: "Hungary", value: "hungary" },
  { label: "Iceland", value: "iceland" },
  { label: "India", value: "india" },
  { label: "Indonesia", value: "indonesia" },
  { label: "Iran", value: "iran" },
  { label: "Iraq", value: "iraq" },
  { label: "Ireland", value: "ireland" },
  { label: "Isle of Man", value: "isle-of-man" },
  { label: "Israel", value: "israel" },
  { label: "Italy", value: "italy" },
  { label: "Ivory Coast", value: "ivory-coast" },
  { label: "Jamaica", value: "jamaica" },
  { label: "Japan", value: "japan" },
  { label: "Jersey", value: "jersey" },
  { label: "Jordan", value: "jordan" },
  { label: "Kazakhstan", value: "kazakhstan" },
  { label: "Kenya", value: "kenya" },
  { label: "Kiribati", value: "kiribati" },
  { label: "Kosovo", value: "kosovo" },
  { label: "Kuwait", value: "kuwait" },
  { label: "Kyrgyzstan", value: "kyrgyzstan" },
  { label: "Lao", value: "lao" },
  { label: "Latvia", value: "latvia" },
  { label: "Lebanon", value: "lebanon" },
  { label: "Lesotho", value: "lesotho" },
  { label: "Liberia", value: "liberia" },
  { label: "Libya", value: "libya" },
  { label: "Liechtenstein", value: "liechtenstein" },
  { label: "Lithuania", value: "lithuania" },
  { label: "Luxembourg", value: "luxembourg" },
  { label: "Macau", value: "macau" },
  { label: "Madagascar", value: "madagascar" },
  { label: "Malawi", value: "malawi" },
  { label: "Malaysia", value: "malaysia" },
  { label: "Maldives", value: "maldives" },
  { label: "Mali", value: "mali" },
  { label: "Malta", value: "malta" },
  { label: "Martinique", value: "martinique" },
  { label: "Mauritania", value: "mauritania" },
  { label: "Mauritius", value: "mauritius" },
  { label: "Mexico", value: "mexico" },
  { label: "Moldova", value: "moldova" },
  { label: "Monaco", value: "monaco" },
  { label: "Mongolia", value: "mongolia" },
  { label: "Montenegro", value: "montenegro" },
  { label: "Montserrat", value: "montserrat" },
  { label: "Morocco", value: "morocco" },
  { label: "Mozambique", value: "mozambique" },
  { label: "Myanmar", value: "myanmar" },
  { label: "Namibia", value: "namibia" },
  { label: "Nepal", value: "nepal" },
  { label: "Netherlands", value: "netherlands" },
  { label: "New Caledonia", value: "new-caledonia" },
  { label: "New Zealand", value: "new-zealand" },
  { label: "Nicaragua", value: "nicaragua" },
  { label: "Niger", value: "niger" },
  { label: "Nigeria", value: "nigeria" },
  { label: "North Korea", value: "north-korea" },
  { label: "North Macedonia", value: "macedonia" },
  { label: "Norway", value: "norway" },
  { label: "Oman", value: "oman" },
  { label: "Pakistan", value: "pakistan" },
  { label: "Panama", value: "panama" },
  { label: "Papua New Guinea", value: "papua-new-guinea" },
  { label: "Paraguay", value: "paraguay" },
  { label: "Peru", value: "peru" },
  { label: "Philippines", value: "philippines" },
  { label: "Poland", value: "poland" },
  { label: "Portugal", value: "portugal" },
  { label: "Puerto Rico", value: "puerto-rico" },
  { label: "Qatar", value: "qatar" },
  { label: "Romania", value: "romania" },
  { label: "Russia", value: "russia" },
  { label: "Rwanda", value: "rwanda" },
  { label: "Saint Kitts and Nevis", value: "saint-kitts-and-nevis" },
  { label: "Saint Lucia", value: "saint-lucia" },
  { label: "Saint Martin", value: "saint-martin" },
  {
    label: "Saint Vincent and the Grenadines",
    value: "saint-vincent-and-the-grenadines",
  },
  { label: "Samoa", value: "samoa" },
  { label: "San Marino", value: "san-marino" },
  { label: "Sao Tome and Principe", value: "sao-tome-and-principe" },
  { label: "Saudi Arabia", value: "saudi-arabia" },
  { label: "Senegal", value: "senegal" },
  { label: "Serbia", value: "serbia" },
  { label: "Seychelles", value: "seychelles" },
  { label: "Sierra Leone", value: "sierra-leone" },
  { label: "Singapore", value: "singapore" },
  { label: "Sint Maarten", value: "sint-maarten" },
  { label: "Slovakia", value: "slovakia" },
  { label: "Slovenia", value: "slovenia" },
  { label: "Solomon Islands", value: "solomon-islands" },
  { label: "Somalia", value: "somalia" },
  { label: "South Africa", value: "south-africa" },
  { label: "South Korea", value: "south-korea" },
  { label: "South Sudan", value: "south-sudan" },
  { label: "Spain", value: "spain" },
  { label: "Sri Lanka", value: "sri-lanka" },
  { label: "Sudan", value: "sudan" },
  { label: "Suriname", value: "suriname" },
  { label: "Sweden", value: "sweden" },
  { label: "Switzerland", value: "switzerland" },
  { label: "Syria", value: "syria" },
  { label: "Taiwan", value: "taiwan" },
  { label: "Tajikistan", value: "tajikistan" },
  { label: "Tanzania", value: "tanzania" },
  { label: "Thailand", value: "thailand" },
  { label: "Togo", value: "togo" },
  { label: "Tonga", value: "tonga" },
  { label: "Trinidad and Tobago", value: "trinidad-and-tobago" },
  { label: "Tunisia", value: "tunisia" },
  { label: "Turkey", value: "turkey" },
  { label: "Turkmenistan", value: "turkmenistan" },
  { label: "Turks and Caicos Islands", value: "turks-and-caicos-islands" },
  { label: "Uganda", value: "uganda" },
  { label: "Ukraine", value: "ukraine" },
  { label: "United Arab Emirates", value: "uae" },
  { label: "United Kingdom", value: "united-kingdom" },
  { label: "Uruguay", value: "uruguay" },
  { label: "US Virgin Islands", value: "us-virgin-islands" },
  { label: "USA", value: "usa" },
  { label: "Uzbekistan", value: "uzbekistan" },
  { label: "Vanuatu", value: "vanuatu" },
  { label: "Vatican City", value: "vatican-city" },
  { label: "Venezuela", value: "venezuela" },
  { label: "Vietnam", value: "vietnam" },
  { label: "Yemen", value: "yemen" },
  { label: "Zambia", value: "zambia" },
  { label: "Zimbabwe", value: "zimbabwe" },
];

export default countries;
